// Code generated by github.com/Karitham/handlergen. DO NOT EDIT.
package main

import (
	"encoding/json"
	"net/http"
)

type errorHandler = func(w http.ResponseWriter, r *http.Request, err error)

var defaultErrHandler = func(w http.ResponseWriter, r *http.Request, err error) {
	http.Error(w, "invalid payload", 400)
}

type Main interface {
	GetBookByName(http.ResponseWriter, *http.Request, string)
	StoreBook(http.ResponseWriter, *http.Request, Book)
}

func GetBookByName(h Main, errHandler ...errorHandler) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		query := r.URL.Query()
		Name := query.Get("name")

		h.GetBookByName(
			w,
			r,
			Name,
		)
	}
}

func StoreBook(h Main, errHandler ...errorHandler) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		var body Book
		if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
			if errHandler == nil {
				defaultErrHandler(w, r, err)
				return
			}
			errHandler[0](w, r, err)
			return
		}
		h.StoreBook(
			w,
			r,
			body,
		)
	}
}
