// Code generated by github.com/Karitham/handlergen. DO NOT EDIT.
package main

import (
	"encoding/json"
	"net/http"
)

func GetBookByName(handler func(w http.ResponseWriter, r *http.Request, Name string)) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		query := r.URL.Query()
		Name := query.Get("name")

		handler(
			w,
			r,
			Name,
		)
	}
}

func StoreBook(handler func(w http.ResponseWriter, r *http.Request, body Book)) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		var body Book
		if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
			http.Error(w, "invalid body", 400)
			return
		}

		handler(
			w,
			r,
			body,
		)
	}
}
