// Code generated by github.com/Karitham/handlergen. DO NOT EDIT.
package handlers

import (
	"encoding/json"
	"net/http"
	"strconv"

	"github.com/Karitham/handlergen/gen"
)

func example1(handler func(w http.ResponseWriter, r *http.Request, UserId int, body gen.Template)) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		query := r.URL.Query()
		queryUserId := query.Get("user_id")
		UserId, err := strconv.Atoi(queryUserId)
		if err != nil {
			http.Error(w, "invalid query", 400)
			return
		}

		var body gen.Template
		if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
			http.Error(w, "invalid body", 400)
			return
		}

		handler(
			w,
			r,
			UserId,
			body,
		)
	}
}
