// Code generated by github.com/Karitham/handlergen. DO NOT EDIT.
package handlers

import (
	"encoding/json"
	"github.com/Karitham/handlergen/gen"
	"net/http"
	"strconv"
)

type Handlers interface {
	example1(http.ResponseWriter, *http.Request, int, gen.Template)
}

func Example1(h Handlers) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		query := r.URL.Query()
		queryUserId := query.Get("user_id")
		UserId, err := strconv.Atoi(queryUserId)
		if err != nil {
			http.Error(w, "invalid query", 400)
			return
		}

		var body gen.Template
		if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
			http.Error(w, "invalid body", 400)
			return
		}

		h.example1(
			w,
			r,
			UserId,
			body,
		)
	}
}
