// Code generated by github.com/Karitham/handlergen. DO NOT EDIT.
package handlers

import (
	"github.com/go-chi/chi/v5"
	"net/http"
	"strconv"
	"strings"
)

func GetUserLogin(handler func(w http.ResponseWriter, r *http.Request, Username, Password string)) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		query := r.URL.Query()
		Username := query.Get("username")
		Password := query.Get("password")

		handler(
			w,
			r,
			Username,
			Password,
		)
	}
}

func GetPetByPetId(handler func(w http.ResponseWriter, r *http.Request, PetId int)) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		query := r.URL.Query()
		queryPetId := chi.URLParam(r, "petId")
		PetId, err := strconv.Atoi(queryPetId)
		if err != nil {
			http.Error(w, "invalid query", 400)
			return
		}

		handler(
			w,
			r,
			PetId,
		)
	}
}

func PostPetByPetId(handler func(w http.ResponseWriter, r *http.Request, PetId int, Name, Status string)) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		query := r.URL.Query()
		queryPetId := chi.URLParam(r, "petId")
		PetId, err := strconv.Atoi(queryPetId)
		if err != nil {
			http.Error(w, "invalid query", 400)
			return
		}
		Name := query.Get("name")
		Status := query.Get("status")

		handler(
			w,
			r,
			PetId,
			Name,
			Status,
		)
	}
}

func DeletePetByPetId(handler func(w http.ResponseWriter, r *http.Request, ApiKey string, PetId int)) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		query := r.URL.Query()
		ApiKey := r.Header.Get("api_key")
		queryPetId := chi.URLParam(r, "petId")
		PetId, err := strconv.Atoi(queryPetId)
		if err != nil {
			http.Error(w, "invalid query", 400)
			return
		}

		handler(
			w,
			r,
			ApiKey,
			PetId,
		)
	}
}

func PostPetByPetIdUploadImage(handler func(w http.ResponseWriter, r *http.Request, PetId int, AdditionalMetadata string)) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		query := r.URL.Query()
		queryPetId := chi.URLParam(r, "petId")
		PetId, err := strconv.Atoi(queryPetId)
		if err != nil {
			http.Error(w, "invalid query", 400)
			return
		}
		AdditionalMetadata := query.Get("additionalMetadata")

		handler(
			w,
			r,
			PetId,
			AdditionalMetadata,
		)
	}
}

func GetStoreOrderByOrderId(handler func(w http.ResponseWriter, r *http.Request, OrderId int)) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		query := r.URL.Query()
		queryOrderId := chi.URLParam(r, "orderId")
		OrderId, err := strconv.Atoi(queryOrderId)
		if err != nil {
			http.Error(w, "invalid query", 400)
			return
		}

		handler(
			w,
			r,
			OrderId,
		)
	}
}

func DeleteStoreOrderByOrderId(handler func(w http.ResponseWriter, r *http.Request, OrderId int)) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		query := r.URL.Query()
		queryOrderId := chi.URLParam(r, "orderId")
		OrderId, err := strconv.Atoi(queryOrderId)
		if err != nil {
			http.Error(w, "invalid query", 400)
			return
		}

		handler(
			w,
			r,
			OrderId,
		)
	}
}

func GetUserByUsername(handler func(w http.ResponseWriter, r *http.Request, Username string)) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		query := r.URL.Query()
		Username := chi.URLParam(r, "username")

		handler(
			w,
			r,
			Username,
		)
	}
}

func PutUserByUsername(handler func(w http.ResponseWriter, r *http.Request, Username string)) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		query := r.URL.Query()
		Username := chi.URLParam(r, "username")

		handler(
			w,
			r,
			Username,
		)
	}
}

func DeleteUserByUsername(handler func(w http.ResponseWriter, r *http.Request, Username string)) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		query := r.URL.Query()
		Username := chi.URLParam(r, "username")

		handler(
			w,
			r,
			Username,
		)
	}
}

func GetPetFindByStatus(handler func(w http.ResponseWriter, r *http.Request, Status string)) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		query := r.URL.Query()
		Status := query.Get("status")

		handler(
			w,
			r,
			Status,
		)
	}
}

func GetPetFindByTags(handler func(w http.ResponseWriter, r *http.Request, Tags []string)) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		query := r.URL.Query()
		queryTags := query.Get("tags")
		Tags := strings.Split(queryTags, ",")

		handler(
			w,
			r,
			Tags,
		)
	}
}
